import Head from 'next/head';
import Cart from '~/components/elemnt/cart';
import Loading from '~/components/elemnt/loading';
import { api } from '~/utils/api';
import { ScrollArea } from '@radix-ui/themes';
export default function Home() {
  const posts = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>iBlog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScrollArea type="always" scrollbars="vertical">
        <main className="grid grid-cols-12 items-center justify-center gap-5 p-5  ">
          {!posts.isLoading ? (
            posts.data?.map((item) => <Cart refetch={posts.refetch} key={item.id} {...item} />)
          ) : (
            <Loading />
          )}
        </main>
      </ScrollArea>
    </>
  );
}
